services:
#    oc_trick.example:
#        class: OC\TrickBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    oc_trick.trickmanager:
        class: OC\TrickBundle\Service\TrickManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
